remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: Awesome Salesforce - Curated List of Resources, Tools and Utilities by Clientell
description: A curated list of awesome Salesforce resources, tools, and utilities maintained by Clientell
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/Clientell-Ai/awesome-salesforce

# Theme customization - Clientell colors
colors:
  header: "#00a1e0"  # Salesforce blue
  gradient_left: "#0176d3"  # Darker shade
  gradient_right: "#00a1e0"  # Salesforce blue

# Open Graph configuration
url: https://clientell-ai.github.io/awesome-salesforce
og_image: /assets/images/og-image.png
keywords:
  - Salesforce
  - Awesome
  - Clientell
  - CRM
