remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: Clientell's Salesforce Awesome List
description: A curated list of awesome Salesforce resources, tools, and utilities maintained by Clientell
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/Clientell-Ai/awesome-salesforce-clientell

# Theme customization - Clientell colors
colors:
  header: "#00a1e0"  # Salesforce blue
  gradient_left: "#0176d3"  # Darker shade
  gradient_right: "#00a1e0"  # Salesforce blue
